# Generated by Django 4.1.7 on 2023-02-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spare_part',
            fields=[
                ('spid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('price', models.FloatField(default=0.0)),
                ('net', models.IntegerField(default=0)),
                ('picture', models.ImageField(default='', upload_to='static/SparePart/')),
            ],
        ),
    ]
