# Generated by Django 4.1.7 on 2023-02-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('aid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('birthdate', models.DateField(default=None)),
                ('picture', models.ImageField(default='', upload_to='static/admin/')),
                ('password', models.CharField(default='1234', max_length=255)),
            ],
        ),
    ]
