# Generated by Django 4.1.7 on 2023-02-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('mid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('birthdate', models.DateField(default=None)),
                ('picture', models.ImageField(default='', upload_to='static/admin/')),
                ('address', models.TextField(default='', max_length=400)),
                ('tel', models.CharField(default='', max_length=20)),
                ('password', models.CharField(default='1234', max_length=255)),
            ],
        ),
    ]
