# Generated by Django 4.1.7 on 2023-02-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0003_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=models.ImageField(default='', upload_to='static/member/'),
        ),
    ]
