# Generated by Django 4.1.7 on 2023-02-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0004_alter_member_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Getjop',
            fields=[
                ('gid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('details', models.CharField(default='', max_length=50)),
                ('date', models.DateField(default=None)),
                ('name_employer', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
