# Generated by Django 4.1.7 on 2023-02-24 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0007_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='details',
        ),
    ]
