# Generated by Django 4.1.7 on 2023-02-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0008_remove_assignment_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savejob',
            fields=[
                ('sid', models.CharField(default='', max_length=13, primary_key=True, serialize=False)),
                ('date', models.DateField(default=None)),
                ('details', models.CharField(default='', max_length=100)),
                ('spare_part', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.spare_part')),
            ],
        ),
    ]
