# Generated by Django 4.1.7 on 2023-02-25 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0009_savejob'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavejobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.assignment')),
                ('savejob', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.savejob')),
            ],
        ),
        migrations.CreateModel(
            name='Samplesale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datesale', models.DateField(default=None)),
                ('amount', models.IntegerField(default=0)),
                ('getjop', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.getjop')),
                ('member', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.member')),
                ('spare_part', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.spare_part')),
            ],
        ),
    ]
