# Generated by Django 4.1.7 on 2023-02-25 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0011_savejob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savejob',
            name='status',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.CreateModel(
            name='Confirms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savejob', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.savejob')),
            ],
        ),
    ]
