# Generated by Django 4.1.7 on 2023-02-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0012_alter_savejob_status_confirms'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
