# Generated by Django 4.1.7 on 2023-02-25 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProfileApp', '0013_assignment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmsAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ProfileApp.assignment')),
            ],
        ),
    ]
